#!/usr/bin/env zsh

watch() {
    local file="$1"
    local std="${2:-c++17}"

    ls ./cc/*.cc |
        entr -r -s "clear && ./scripts compile ${file} ${std} && echo '\n======\n' && ./build/${file}"
}

compile() {
    local file="$1"
    local std="${2:-c++17}"

    g++ -std=${std} ./cc/${file}.cc -o ./build/${file}
}

case $1 in
watch)
    shift
    watch $@
    ;;
compile)
    shift
    compile $@
    ;;
esac
