#!/usr/bin/env zsh

watch() {
    local file="$1"
    ls ./cpp/*.cpp |
        entr -r -s "clear && ./scripts compile ${file} && echo '\n======\n' && ./build/${file}"
}

compile() {
    local file="$1"

    g++ ./cpp/${file}.cpp -o ./build/${file} $(root-config --cflags --libs)
}

run() {
    local file="$1"

    ./scripts compile ${file}
    ./build/${file}
}

"$@"
